version: '3.1'

services:
  symfony:
    container_name: symfony
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/
    networks:
      - backroom-nt
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      [ "1010:5432" ]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
        [ ./pqsql:/var/www/pqsql/ ]
    networks:
      - backroom-nt
  nuxtjs:
    container_name: nuxtjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      [ "3000:3000" ]
    volumes:
        [ ./frontend:/frontend/ ]
    networks:
      - backroom-nt
networks:
  backroom-nt:
    driver: bridge


