version: '3.1'

services:
  symfony:
    image: docker.io/bitnami/symfony:6.2
    restart: always
    ports:
      - '81:8000'
    environment:
      - ALLOW_EMPTY_PASSWORD=${SYMFONY_ALLOW_EMPTY_PASSWORD}
      - SYMFONY_DATABASE_HOST=${DATABASE_HOST}
      - SYMFONY_DATABASE_PORT_NUMBER=${DATABASE_PORT_NUMBER}
      - SYMFONY_DATABASE_USER=${DATABASE_USER}
      - SYMFONY_DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - './:/app'
    depends_on:
      - postgres
    networks:
      - backroom-nt
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      [ "1010:5432" ]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
        [ ./pqsql:/var/www/pqsql/ ]
    networks:
      - backroom-nt
  nuxtjs:
    container_name: nuxtjs
    image: nuxtjs
    restart: always
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      [ "3000:3000" ]
    volumes:
        [ ./frontend:/frontend/ ]
    networks:
      - backroom-nt
networks:
  backroom-nt:
    driver: bridge


