<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYb41RRU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYb41RRU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYb41RRU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYb41RRU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYb41RRU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yb41RRU',
    'container.build_id' => 'f1e739ed',
    'container.build_time' => 1677363480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYb41RRU');
