<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRaMdWS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRaMdWS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKRaMdWS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKRaMdWS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKRaMdWS\App_KernelDevDebugContainer([
    'container.build_hash' => 'KRaMdWS',
    'container.build_id' => 'f991fb12',
    'container.build_time' => 1679429957,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRaMdWS');
