<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD0paioG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD0paioG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD0paioG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD0paioG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD0paioG\App_KernelDevDebugContainer([
    'container.build_hash' => 'D0paioG',
    'container.build_id' => 'ff2b9fc4',
    'container.build_time' => 1682428066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD0paioG');
