vich_uploader:
    db_driver: orm
    metadata:
      type: attribute
    mappings:
      media_object:
        uri_prefix: /profile
        upload_destination: '%kernel.project_dir%/media/profile'
        # Will rename uploaded files using a uniqueid as a prefix.
        namer: Vich\UploaderBundle\Naming\OrignameNamer
